#!/bin/bash

# JUST IGNORE: BASH SCRIPT ONLY

# wipe docker image and container
if [[ "$1" == "reset" ]];then
	docker ps -aq && \
	docker stop $(docker ps -aq) && \
	docker system prune --all && \ 
	docker volume prune --all
fi

# enter container
if [[ "$1" == "start-api" ]];then
	docker run --network kitra_kitranet -p 3030:3030 -v ./:/kitra-app -w /kitra-app -it 13617ec9193b /bin/sh
fi
