version: "3.9"

services:
  api:
    build:
      context: .
    ports:
      - "3030:3030"
    volumes:
      - ./:/kitra-app
    working_dir: /kitra-app
    networks:
      - kitranet
    depends_on:
      - db

  db:
    image: mariadb:10.3
    restart: always
    ports:
     - "3306:3306"
    environment:
      MYSQL_DATABASE: kitra_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - kitranet

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:8080
    environment:
      - PMA_ARBITRARY=1
    networks:
      - kitranet
    depends_on:
      - db

networks:
  kitranet:
    driver: bridge
