version: "3"

services:
  api:
    image: node:20.12.2-alpine
    ports:
      - "3030:3030"
    volumes:
      - ./:/kitra-app
    working_dir: /kitra-app
    entrypoint: ["sh", "-c", "npm install"]
    networks:
      - kitranet

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
     - "3306:3306"
    environment:
      MYSQL_DATABASE: kitra-db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    networks:
      - kitranet

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - kitranet

networks:
  kitranet:
    driver: bridge
