version: "3.9"

services:
  db:
    image: mariadb:10.3
    restart: always
    ports:
     - "3306:3306"
    environment:
      MYSQL_DATABASE: kitra_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - kitranet
    healthcheck:
      test: ps aux | grep mysqld
      interval: 10s
      retries: 10
      timeout: 5s
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - kitranet

  api:
    image: node:lts-alpine
    ports:
      - "3030:3030"
    volumes:
      - ./:/kitra-app
    working_dir: /kitra-app
    command: 
        sh -c "npm install && \
        npm run migrate && \
        npm start"
    networks:
      - kitranet
    depends_on:
      db:
        condition: service_healthy 

networks:
  kitranet:
    driver: bridge